# Generated by Django 2.1.4 on 2019-02-07 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_auto_20190207_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='gerencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogos.Gerencia'),
            preserve_default=False,
        ),
    ]
