# Generated by Django 2.1.4 on 2019-02-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_supervisor_gerencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='clli',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
