# Generated by Django 2.1.4 on 2019-02-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_auto_20190208_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecutor',
            name='activo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gerencia',
            name='activo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localidad',
            name='activo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicios',
            name='activo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='activo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
