# Generated by Django 2.1.4 on 2019-02-08 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_auto_20190208_0120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicios',
            new_name='Servicio',
        ),
    ]
