# Generated by Django 2.1.4 on 2019-02-22 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('actividad', models.CharField(max_length=2)),
                ('contacto', models.CharField(max_length=10)),
                ('asunto', models.CharField(max_length=50)),
                ('detalle', models.CharField(max_length=250)),
                ('fecha_inicio', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('fecha_fin', models.DateField()),
                ('hora_fin', models.TimeField()),
                ('fecha_inicio_afectacion', models.DateField(blank=True, null=True)),
                ('hora_inicio_afectacion', models.TimeField(blank=True, null=True)),
                ('fecha_fin_afectacion', models.DateField(blank=True, null=True)),
                ('hora_fin_afectacion', models.TimeField(blank=True, null=True)),
                ('mop', models.FileField(upload_to='mops')),
                ('clientes_afectados', models.CharField(blank=True, max_length=500, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=250, null=True)),
                ('ejecutores', models.ManyToManyField(to='catalogos.Ejecutor')),
                ('gerencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Gerencia')),
                ('localidades', models.ManyToManyField(to='catalogos.Localidad')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Proveedor')),
                ('servicios', models.ManyToManyField(blank=True, to='catalogos.Servicio')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Supervisor')),
            ],
        ),
    ]
