# Generated by Django 2.1.4 on 2019-02-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estatus',
            field=models.IntegerField(default=0),
        ),
    ]
