# Generated by Django 2.1.4 on 2019-02-16 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_auto_20190208_0156'),
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='asunto',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='detalle',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='gerencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogos.Gerencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='supervisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogos.Supervisor'),
            preserve_default=False,
        ),
    ]
