# Generated by Django 2.1.4 on 2019-02-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='log',
            field=models.TextField(default='Orden creada en 2019-02-27 20:16:48.172621'),
        ),
    ]
