# Generated by Django 2.1.4 on 2019-02-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_auto_20190216_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='contacto',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
