# Generated by Django 2.1.4 on 2019-02-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_orden_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='log',
            field=models.TextField(default='Orden creada en 2019-02-22 16:45:06.124194'),
        ),
    ]
