# Generated by Django 2.1.4 on 2019-02-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_orden_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='actividad',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
