# Generated by Django 2.1.4 on 2019-02-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_auto_20190208_0156'),
        ('ordenes', '0004_orden_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='localidades',
            field=models.ManyToManyField(to='catalogos.Localidad'),
        ),
    ]
