# Generated by Django 2.1.4 on 2019-03-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_auto_20190227_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
